spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service  # Маршрутизация к product-service через Eureka
          predicates:
            - Path=/products/**
        - id: order-service
          uri: lb://order-service  # Маршрутизация к order-service через Eureka
          predicates:
            - Path=/orders/**
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/  # Адрес Eureka Server
